[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile.aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./docker/Dockerfile.armv7-unknown-linux-gnueabihf"
